# Generated by Django 5.2.6 on 2025-10-17 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projeto/imagens/')),
                ('servidor_solicitante', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('setor_lotacao', models.CharField(max_length=20)),
                ('ano_deposito', models.CharField(max_length=4)),
                ('link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='projeto/certificados/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='vitrine.campus')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='vitrine.categoria')),
            ],
        ),
    ]
