# Generated by Django 5.2.6 on 2025-10-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='AreaConhecimento',
        ),
        migrations.RenameModel(
            old_name='ProjetoCategoria',
            new_name='ProjetoArea',
        ),
        migrations.AddField(
            model_name='projeto',
            name='autores',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
