# Generated by Django 5.2.6 on 2025-10-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
