# Generated by Django 5.2.6 on 2025-10-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_rename_categoria_projeto_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='categorias',
        ),
        migrations.AddField(
            model_name='projeto',
            name='categorias',
            field=models.ManyToManyField(related_name='projetos', to='vitrine.categoria'),
        ),
    ]
