# Generated by Django 5.2.6 on 2025-10-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_rename_categoria_areaconhecimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='img',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='nome',
            new_name='titulo',
        ),
    ]
