# Generated by Django 5.2.6 on 2025-10-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_remove_projeto_categorias_projeto_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='projetos/certificados/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/imagens/'),
        ),
    ]
