# Generated by Django 5.2.6 on 2025-10-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_rename_img_projeto_imagem_rename_nome_projeto_titulo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaConhecimento',
            new_name='Categoria',
        ),
        migrations.AddField(
            model_name='projeto',
            name='areas_conhecimento',
            field=models.ManyToManyField(related_name='projetos', to='vitrine.categoria'),
        ),
        migrations.DeleteModel(
            name='ProjetoArea',
        ),
    ]
