# Generated by Django 5.2.6 on 2025-11-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_alter_projeto_certificado_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('Em Andamento', 'Em Andamento'), ('Concluído', 'Concluido'), ('Parado', 'Parado')], default='em andamento', max_length=50),
        ),
    ]
